### ISSUE TITLE
How to experiment with IoT Devices and sensors?

### ISSUE THREAD

**Issue by gun007DK** [porrey/iot#1]
Hi
I want to download and try these libraries on my local PC.
I'm new to this. Is it possible to become a collaborator on the project or how can I do it?

**Comment by porrey** [comment]
These libraries are used to support projects at hackster.io/Porrey. Feel free to use them in any way you wish. If you find issues or want to add to them, just create a pull request. Let me know if you have any other questions.

**Comment by gun007DK** [comment]
Thank You very much.
I do have a question though I might find the answer on the web.
What is the difference between making a fork or making a branch at github?
I will try to use your projects in my projects which is about using Raspberry Pi to IoT.


Fra: Daniel Porrey [mailto:notifications@github.com]
Sendt: 7. juli 2017 22:33
Til: porrey/iot
Cc: egonj; Author
Emne: Re: [porrey/iot] How to experiment with IoT Devices and sensors? (#1)


These libraries are used to support projects at huckster.io/Porrey. Feel free to use them in any way you wish. If you find issues or want to add to them, just create a pull request. Let me know if you have any other questions.

**Comment by porrey** [comment]
Fork is used either to experiment with changes to a library or to start a new library from an existing library.

Branching is core to GitHub and is used inside a repo to manage versions/changes. The rule to follow in GitHub is that the Master branch is always releasable and branches are used for new releases or to experiment with changes. Branching is very useful for when you are working on a new release and have to fix a bug in the previous release. You would create a branch from master, test and release it. Later that branch would be merged into the new release branch.

A pull request is used when you want to make/suggest a change to someone else's library but you do not have direct access or are not part of the primary development team.
